### ISSUE TITLE
Gerrit Trigger SSH often gets stuck in CLOSED WAITING

### ISSUE THREAD

**Issue by thadguidry** [sonyxperiadev/gerrit-events#70]
We have seen this issue occur multiple times (once a day) on Ubuntu 14 and 16 and multiple servers.
Gerrit Trigger threads set to 3 on Jenkins.  Using latest Gerrit Trigger 2.24.0

We see the SSH connections in CLOSED_WAITING we decided to take a heap dump to assist the team in helping us debug the issue. Can open and browse in Java VisualVM
https://drive.google.com/open?id=0B533WzlrxWraVHZEU01MSnpXcW8

Related to #66 #68  #69 ??

**Comment by rinrinne** [comment]
What is "CLOSED_WAITING"? I don't know such status name. Googling but not found.

**Comment by rinrinne** [comment]
Maybe not CLOSED_WAITING but TIMED_WAITING, it is one of thread status that is defined by `Thread.State`.

I checked heapdump with jvisualvm.

* Observed a lot of `RefReplicated` event objects.
* `ReplicationCache` has a lot of `RefReplicatedId` instance.
* Cannot get actual thread status from heapdump because it is managed by class field in `sum.misc.VM`.

Maybe your system has gerrit slave then do replication. I guess your issue is caused by replication status.

If you are facing issue related to #66, #68, #69, event object is no longer generated. To identify the root cause, you need to get more heapdump.

**Comment by thadguidry** [comment]
@rinrinne will try to get more heap dumps.

**Comment by thadguidry** [comment]
We are no longer see this specific issue of the port not being ESTABLISHED, but in a CLOSED_blah state.
